<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理后台首页</title>
    <link href="<?= BASE_URL?>/application/library/bootstrap-3.3.7/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="<?= BASE_URL?>/application/library/bootstrap-3.3.7/dist/js/bootstrap.min.js" type="text/javascript"></script>
</head>
<body>


    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">自媒体系统管理后台</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">首页</a></li>
                    <li><a href="<?= BASE_URL?>index.php/index/message/addMessage/userName/<?php echo $userName?>">添加文章</a></li>
                    <li><a href="<?= BASE_URL?>index.php/index/message/selectMessage/userName/<?php echo $userName?>">更新文章</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="jumbotron">
        <div class="container">
            <h1>Hello,<?php echo $userName?>!</h1>
        </div>
    </div>
</body>
</html>